# Generated by Django 6.0.4 on 2026-04-27 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0002_alter_destination_created_at"),
        ("webhooks", "0002_alter_webhookevent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_url", models.URLField(max_length=2048)),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body", models.JSONField(default=dict)),
                (
                    "response_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_headers", models.JSONField(default=dict)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_attempts",
                        to="destinations.destination",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="webhooks.webhookevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "attempt_number"],
                        name="deliveries__event_i_4a577c_idx",
                    ),
                    models.Index(
                        fields=["destination", "status", "-created_at"],
                        name="deliveries__destina_e0af0d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "attempt_number"),
                        name="unique_attempt_number_per_event",
                    )
                ],
            },
        ),
    ]
