# Generated by Django 6.0.4 on 2026-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("webhook.received", "Webhook received"),
                    ("delivery.succeeded", "Delivery succeeded"),
                    ("delivery.failed", "Delivery failed"),
                    ("event.replayed", "Event replayed"),
                    ("event.cancelled", "Event cancelled"),
                    ("signature.failed", "Signature failed"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
