# Generated by Django 6.0.4 on 2026-04-27 05:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0002_alter_destination_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("method", models.CharField(max_length=10)),
                ("headers", models.JSONField(default=dict)),
                ("query_params", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("delivering", "Delivering"),
                            ("success", "Success"),
                            ("retrying", "Retrying"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_events",
                        to="destinations.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["destination", "status", "-received_at"],
                        name="webhooks_we_destina_05c024_idx",
                    ),
                    models.Index(
                        fields=["payload_hash"], name="webhooks_we_payload_d9ead7_idx"
                    ),
                ],
            },
        ),
    ]
