# Generated by Django 6.0.4 on 2026-04-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhookevent",
            options={
                "ordering": ["-received_at"],
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
            },
        ),
    ]
