# Generated by Django 6.0.4 on 2026-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_alter_destination_created_at"),
        ("webhooks", "0002_alter_webhookevent_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("destination", "idempotency_key"),
                name="unique_idempotency_key_per_destination",
            ),
        ),
    ]
