# Generated by Django 6.0.4 on 2026-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_alter_destination_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="incoming_signature_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="destination",
            name="signature_verification_mode",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("generic_hmac_sha256", "Generic HMAC SHA256"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
